# site info

#  language codes https://www.w3schools.com/tags/ref_language_codes.asp
# territory codes https://www.w3schools.com/tags/ref_country_codes.asp

lang: zh-Hans # default language tag of the site.
locale: zh_CN # og:locale of the format language_TERRITORY.
author: "onep1us" # name of site's author
title: onep1us 的博客 # name of the site
description: > # description of the site (multiple lines allowed)
  一个简单而干净的个人博客，记录技术与生活。
url: https://onep1us.github.io # the base hostname & protocol for your site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
# webmaster_verifications: # verify ownership with several search services
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234

# favicon & app icon

# generate modern svg favicon at https://realfavicongenerator.net/svg-favicon/
# generate png icons pack at https://realfavicongenerator.net/
# generate maskable chrome icons at https://maskable.app/editor/

# favicon:
#  ico: "/favicon.ico" # legacy 'favicon.ico' at the root folder of your site, it is highly recommended not changing this name
#  svg: "/favicon.svg" # name+extension of modern vector favicon
#  ios: "/maskable-180x180.png" # icon for Safari
# webmanifest: "/site.webmanifest" # icon config file path for PWA

# pwa

# pwa:
#   enabled: false # set false to temporarily disable this plugin
#   sw_src_filepath: service-worker.js # Optional
#   sw_dest_filename: service-worker.js # Optional
#   dest_js_directory: assets/js # Required
#   precache_recent_posts_num: 0 # Optional
#   precache_glob_directory: / # Optional
#   precache_glob_patterns: # Optional
#     - "assets/background/*.{png,svg,gif}"
#     - "assets/css/*.{css}"
#     - "assets/js/*.{js}"
#     - "assets/OpenFont/**/*.{eot,otf,ttf,woff,woff2}"
#   precache_glob_ignores: # Optional
#     - index.html

# theme config

# theme: less-style-please # if you use it as a local theme
remote_theme: feeshy/less-style-please@lite # if you use it as a remote theme on github
# show_logo: true # show the svg favicon in home page and archive page
show_description: true # show blog description in home page
bilingual: false # auto hide lang="zh" elements for non-chinese visitors
# background_image: # path to background images for light and dark mode
#   light: ""
#   dark: ""
search_engine: baidu # available values: google, bing, duckduckgo, baidu
nav:
  back_home: "home" # customize text for homepage link
  tags: "tags" # customize text for tags page link
  go_to_top: "🔝" # customize text for go to top button
  toc: "📖" # customize text for go to top button
  search: "search" # customize text for search page link
copyright: "by" # available values: "all-rights-reserved", "by-nc-nd", "by-nd", "by-nc-sa", "by-nc", "by-sa", "by", "public-domain". choose here https://chooser-beta.creativecommons.org/
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# defaults

permalink: /:categories/:title
jekyll-archives:
  enabled: [year, tags]
  layout: archive
  permalinks: # if you changed these, don't forget to change the codes in '_includes/post_meta.html' as well
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: "*/index.md"
      type: pages
    values:
      layout: archive
  -
    scope:
      path: "assets"
    values:
      sitemap: false
  -
    scope:
      path: life
      type: posts
    values:
      fonts: serif # this activates an alternative set of serif typefaces
    # dropcap: true # this activates a drop cap effect

# build settings

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "highlight", "footnotes"]
toc:
  min_level: 2 # value: 1-6
  max_level: 3 # value: 1-6
sass:
  sass_dir: _sass
  style: compressed
feed:
  posts_limit: 10 # max number of posts on feed

# excluded files from building

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - .github
  - LICENSE.txt
  - README.md

# plugins

plugins:
  - jekyll-remote-theme # enable this if you use it as a remote theme
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-archives
  - jekyll-feed
  - jekyll-toc
  - jekyll-pwa-workbox
  - jekyll-redirect-from
